FAT2-149 -  show message if last start date passed
SkillsFundingAgency/das-findapprenticeshiptraining pull request #22
Opened 2020-08-24 08:34 UTC by robyoung91

2020-08-24 10:48 UTC, PeterDavidWilliams submitted a review, later dismissed

2020-08-24 10:57 UTC, PeterDavidWilliams approved these changes

2020-08-24 15:38 UTC, dashton82 requested changes

2020-08-24 15:38 UTC, dashton82 commented on src/SFA.DAS.FAT.Web.AcceptanceTests/Features/CourseDetail.feature
> +And there is a message and button to course list displayed if course last start date has passed
```suggestion
And there is a message and button to go to course list displayed
```

2020-08-24 15:38 UTC, dashton82 commented on src/SFA.DAS.FAT.Web.AcceptanceTests/Steps/CourseDetailSteps.cs
> +        [Then("there is a message and button to course list displayed if course last start date has passed")]
Will need to be changed to reflect the above comment

2020-08-24 15:38 UTC, dashton82 commented on src/SFA.DAS.FAT.Web.AcceptanceTests/Steps/CourseDetailSteps.cs
> +            if (DateTime.Now > expectedApiResponse.Course.StandardDates.LastDateStarts)
I'd remove this, we'd want it to fail if it doesn't show the below message

2020-08-24 15:38 UTC, dashton82 commented on src/SFA.DAS.FAT.Web/Models/CourseViewModel.cs
> +                AfterLastStartDate = DateTime.Now > course.StandardDates?.LastDateStarts,
Use `DateTime.UtcNow`

2020-08-25 08:12 UTC, dashton82 approved these changes

2020-08-27 15:16 UTC, merged